Feature/schema changes
brain-image-library/bil_site pull request #163
Opened 2021-05-05 19:06 UTC by ltuite96

2021-05-07 20:33 UTC, ecpantalone requested changes
just a few things we want to switch out, mostly those on_delete=models.CASCADE instances to remove orphaned data

2021-05-07 20:33 UTC, ecpantalone commented on ingest/models.py
> +    project_id = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, blank=True)
change to on_delete=models.CASCADE

2021-05-07 20:33 UTC, ecpantalone commented on ingest/models.py
> +    collection_id = models.ForeignKey(Collection, on_delete=models.SET_NULL, null=True, blank=True)
change to on_delete=models.CASCADE

2021-05-07 20:33 UTC, ecpantalone commented on ingest/models.py
> +    project_id = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, blank=True)
change to on_delete=models.CASCADE

2021-05-07 20:33 UTC, ecpantalone commented on ingest/models.py
> +    bil_user_id = models.ForeignKey(BilUser, on_delete=models.SET_NULL, null = True, blank=True)
i think leaving this as on_delete=models.SET_NULL makes sense, because if we remove a bil_user, we don't want to lose their data

2021-05-07 20:33 UTC, ecpantalone commented on ingest/models.py
> +    project_id = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, blank=True)
change to on_delete=models.CASCADE

2021-05-07 20:33 UTC, ecpantalone commented on ingest/models.py
> +    project_id = models.ForeignKey(Project, on_delete = models.SET_NULL, null = True, blank=True)
change to on_delete=models.CASCADE

2021-05-07 20:33 UTC, ecpantalone commented on ingest/models.py
> +    collection_id = models.ForeignKey(Collection, on_delete=models.SET_NULL, null=True, blank=True)
on_delete=models.SET_NULL would be useful here to preserve context historically within this EventsLog model

2021-05-10 14:03 UTC, jpuerto-psc reviewed
Added comments with feedback

2021-05-20 15:33 UTC, merged